/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import osnovneklase.ModelTabeleVozila;
import osnovneklase.Vozila;
import povezivanjesabazom.Kontroler;

/**
 *
 * @author lucca
 */
public class _3_SvaVozila extends javax.swing.JDialog {

    /**
     * Creates new form _3_SvaVozila
     */
    public _3_SvaVozila(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prikaziSvaVozila();
        centrirajSveVrednostiUTabeli();
        sakrijTrenutniBrojRezultataPretragePreKucanja();
        obradiPoljeKojePretrazuje();
        omoguciDaSamoJedanRedMozeBitiSelektovan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVozila = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPretrazi = new javax.swing.JTextField();
        lblBrojRezultata = new javax.swing.JLabel();
        btnObrisi = new javax.swing.JButton();
        btnUnesiNovoVozilo = new javax.swing.JButton();
        lblBrojVozilaTrenutni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("***SVA VOZILA***");
        setBounds(new java.awt.Rectangle(800, 200, 700, 900));
        setMinimumSize(new java.awt.Dimension(700, 200));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        tblVozila.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 2, true));
        tblVozila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVozila.setRowHeight(20);
        tblVozila.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblVozila);

        jLabel1.setText("Pretrazi:");

        txtPretrazi.setForeground(new java.awt.Color(153, 153, 153));
        txtPretrazi.setText("Pretrazi po bilo kom kriterijumu...");
        txtPretrazi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPretraziFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPretraziFocusLost(evt);
            }
        });
        txtPretrazi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPretraziMouseExited(evt);
            }
        });
        txtPretrazi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretraziKeyReleased(evt);
            }
        });

        lblBrojRezultata.setText("lblBrojRezultata");

        btnObrisi.setText("Obrisi");
        btnObrisi.setToolTipText("Obrisi vozilo iz baze");
        btnObrisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnUnesiNovoVozilo.setText("Unesi novo vozilo");
        btnUnesiNovoVozilo.setToolTipText("Unesi novo vozilo u bazu");
        btnUnesiNovoVozilo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnesiNovoVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiNovoVoziloActionPerformed(evt);
            }
        });

        lblBrojVozilaTrenutni.setText("lblBrojVozilaTrenutni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBrojRezultata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 583, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrojVozilaTrenutni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnUnesiNovoVozilo)
                                .addGap(30, 30, 30)
                                .addComponent(btnObrisi)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrojRezultata)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBrojVozilaTrenutni)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnObrisi)
                            .addComponent(btnUnesiNovoVozilo))))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretraziKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretraziKeyReleased
        ModelTabeleVozila table = (ModelTabeleVozila) tblVozila.getModel();
        String pretrazi = txtPretrazi.getText().strip();

        //      String pretrazi2 = txtPretrazi.getText().toUpperCase(); // za registraciju
        TableRowSorter<ModelTabeleVozila> tr = new TableRowSorter<>(table);
        tblVozila.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(pretrazi));

        //       tr.setRowFilter(RowFilter.regexFilter(pretrazi2));
        prikaziTrenutniBrojRezultataPretragePreKucanja();
        int brojRedovaTrenutno = tblVozila.getRowCount();

        if (txtPretrazi.getText().length() != 0) {
            lblBrojRezultata.setText("Broj nadjenih rezultata: " + brojRedovaTrenutno);
            txtPretrazi.setForeground(Color.black);
        } else {
            lblBrojRezultata.setText("");
        }

        if (brojRedovaTrenutno == 0) {
            lblBrojRezultata.setText("Nema nadjenih rezultata za dati kriterijum!");
            txtPretrazi.setForeground(Color.red);
        }


    }//GEN-LAST:event_txtPretraziKeyReleased

    private void txtPretraziFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPretraziFocusLost
        if (txtPretrazi.getText().equals("")) {
            lblBrojRezultata.setText("");
        }

        if (txtPretrazi.getText().isBlank()) {
            txtPretrazi.setText("Pretrazi po bilo kom kriterijumu...");
            txtPretrazi.setForeground(Color.gray);

        } else {
            txtPretrazi.setForeground(Color.black);
        }

    }//GEN-LAST:event_txtPretraziFocusLost

    private void txtPretraziMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPretraziMouseExited

    }//GEN-LAST:event_txtPretraziMouseExited

    private void txtPretraziFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPretraziFocusGained
        if (txtPretrazi.getText().equals("Pretrazi po bilo kom kriterijumu...")) {
            txtPretrazi.setForeground(Color.black);
            txtPretrazi.setText("");
        }
    }//GEN-LAST:event_txtPretraziFocusGained

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        if (tblVozila.getSelectedRow() != -1) {

            try {
                ModelTabeleVozila mtz = (ModelTabeleVozila) tblVozila.getModel();
                String red = tblVozila.getModel().getValueAt(tblVozila.getSelectedRow(), 1).toString();
                Kontroler.getInstance().obrisiVozilo(tblVozila.getModel().getValueAt(tblVozila.getSelectedRow(), 1).toString());
                mtz.obrisiVozilo(tblVozila.getSelectedRow());

                JOptionPane.showMessageDialog(this, "Obrisano je vozilo koje je imalo ID: " + red, "Brisanje uspesno", JOptionPane.INFORMATION_MESSAGE);

                if (!txtPretrazi.getText().equals("Pretrazi po bilo kom kriterijumu...")) {
                    txtPretrazi.setText("Pretrazi po bilo kom kriterijumu...");
                    txtPretrazi.setForeground(Color.gray);

                } else {

                    lblBrojRezultata.setText("");
                }

            } catch (SQLException ex) {
                Logger.getLogger(_3_SvaVozila.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati jedno vozilo za brisanje!", "Greska prilikom brisanja", JOptionPane.ERROR_MESSAGE);

            if (!txtPretrazi.getText().equals("Pretrazi po bilo kom kriterijumu...")) {
                txtPretrazi.setText("Pretrazi po bilo kom kriterijumu...");
                txtPretrazi.setForeground(Color.gray);

            } else {

                lblBrojRezultata.setText("");
            }
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnUnesiNovoVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiNovoVoziloActionPerformed

        _2_PrijemNovogVozilaUServis dialog = new _2_PrijemNovogVozilaUServis(_3_SvaVozila.this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnUnesiNovoVoziloActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        prikaziSvaVozila();
        centrirajSveVrednostiUTabeli();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_3_SvaVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_3_SvaVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_3_SvaVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_3_SvaVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                _3_SvaVozila dialog = new _3_SvaVozila(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnUnesiNovoVozilo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojRezultata;
    private javax.swing.JLabel lblBrojVozilaTrenutni;
    private javax.swing.JTable tblVozila;
    private javax.swing.JTextField txtPretrazi;
    // End of variables declaration//GEN-END:variables

    private void prikaziSvaVozila() {

        odrediVelicinuRedova();
        odrediVelicinuKolona();

        try {
            // popuni tabelu listom

            List<Vozila> listaZaposlenih = Kontroler.getInstance().prikaziSvaVozila();
            tblVozila.setModel(new ModelTabeleVozila(listaZaposlenih));
        } catch (SQLException ex) {
            Logger.getLogger(_3_SvaVozila.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (tblVozila.getRowCount() != 0 && !txtPretrazi.getText().equals("")) {
            lblBrojVozilaTrenutni.setText("Trenutni broj vozila: " + tblVozila.getRowCount());
        } else {
            lblBrojVozilaTrenutni.setText("Trenutno nema vozila u bazi!");
        }

    }

    private void centrirajSveVrednostiUTabeli() {

        // centriraj nazive kolona
        ((DefaultTableCellRenderer) tblVozila.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);

        // centriraj vrednosti u tabeli
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int kolona = 0; kolona < tblVozila.getColumnCount(); kolona++) {
            tblVozila.getColumnModel().getColumn(kolona).setCellRenderer(centerRenderer);
        }

        // omoguci sortiranje za sve kolone (default sortiranje u koje ne mesam svoje prste)
        tblVozila.setAutoCreateRowSorter(true);
    }

    private void sakrijTrenutniBrojRezultataPretragePreKucanja() {
        lblBrojRezultata.setVisible(false);
    }

    private void prikaziTrenutniBrojRezultataPretragePreKucanja() {
        lblBrojRezultata.setVisible(true);
    }

    private void odrediVelicinuKolona() {           // ovo ne radi!!!
        int[] columnsWidth = {
            120, 115, 215, 105, 215, 215, 215, 115, 110, 150, 320
        };

        int i = 0;
        for (int width : columnsWidth) {
            TableColumn column = tblVozila.getColumnModel().getColumn(i++);
            column.setMinWidth(width);
            column.setMaxWidth(width);
            column.setPreferredWidth(width);
        }

    }

    private void odrediVelicinuRedova() {

        tblVozila.setRowHeight(25);

    }

    private void obradiPoljeKojePretrazuje() {

        if (!txtPretrazi.getText().equals("Pretrazi po bilo kom kriterijumu...")) {
            txtPretrazi.setText("Pretrazi po bilo kom kriterijumu...");
            txtPretrazi.setForeground(Color.gray);

        } else {

            lblBrojRezultata.setText("");
        }

    }

    private void omoguciDaSamoJedanRedMozeBitiSelektovan() {
        tblVozila.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
}
